name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  ci_part_docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          imageName: test
          push: true
          tags: igorbibichkov/test:tagname
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
            
  cd_part_heroku: 
    runs-on: ubuntu-latest
    needs: [ci_part_docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Current Path
        run: cd ${{ github.workspace }}/staging && ls -al 
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          run: cd ${{ github.workspace }}/staging && ls -al 
          dockerfile_path: "./" # set the path to the folder wher the Dokerfile is located
            
            
          
                  
          
